title: Li Yijuan | 李懿娟
version: 3.0.0
email: serenalyjuan@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arnica-client.vercel.app" # replace with your Netlify site URL

# Site Settings
dark_header: false
cover_image: /img/ba.jpg
mailclimp_url: 'https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&id=4784863884'
facebook_username: https://www.facebook.com/profile.php?id=100089759058416&mibextid=9R9pXO
twitter_username: https://x.com/serena_lyjuan?t=RVuhMMCMiPkaru_oVax0pA&s=09
linkedin_username: https://www.linkedin.com/in/yijuan-li-1a9634227?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  
permalink: pretty

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/pages/:num/'
  title: ':title - page :num'
  limit: 0  
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail: 
    before: 2
    after: 2
  extension: 'html'
  indexpage: 'index'

autopages:
  enabled: true
  categories: 
    layouts: 
      - 'category.html'
    title: ':cat'
    permalink: '/category/:cat'
  collections:
    layouts: 
      - 'category.html'
    title: ' :coll'
    permalink: '/:coll/'
  tags:
    layouts: 
      - 'tag.html'
    title: ':tag'
    permalink: '/tag/:tag'

tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

collections:
  authors:
    title: Authors
    output: true
    permalink: /authors/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
sass:
  sass_dir: _sass
  style: compressed
